# skills/ppt.py
import os
from datetime import datetime
from pptx import Presentation

from brain.agent import Skill
from core.settings import get_setting

# ============================================================
# POWERPOINT SKILL (ORION v5)
# ============================================================

class PPTSkill(Skill):
    name = "ppt"
    triggers = [
        "ppt",
        "presentation",
        "slides",
        "powerpoint",
        "create slides",
    ]

    def run(self, text: str) -> str:
        if not get_setting("productivity_enabled", True):
            return "Document generation is disabled in settings."

        content = self._extract_content(text)
        path = self._create_ppt(content)
        return f"Presentation created at {path}"

    # ============================================================
    # INTERNAL HELPERS
    # ============================================================

    def _extract_content(self, text):
        """
        Orion v5 used simple heuristics.
        Later this can be replaced with LLM logic.
        """
        keywords = [
            "ppt",
            "presentation",
            "slides",
            "about",
            "on",
        ]

        words = text.split()
        cleaned = [w for w in words if w.lower() not in keywords]

        if not cleaned:
            return "HELION GENERATED PRESENTATION"

        return " ".join(cleaned)

    def _create_ppt(self, topic: str):
        prs = Presentation()

        # Title slide
        slide = prs.slides.add_slide(prs.slide_layouts[0])
        slide.shapes.title.text = topic
        slide.placeholders[1].text = "Generated by HELION"

        # Content slide
        content_slide = prs.slides.add_slide(prs.slide_layouts[1])
        content_slide.shapes.title.text = "Overview"
        content_slide.placeholders[1].text = (
            f"This presentation introduces:\n\n{topic}"
        )

        os.makedirs("generated_ppt", exist_ok=True)
        filename = f"HELION_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}.pptx"
        path = os.path.join("generated_ppt", filename)

        prs.save(path)
        return path

# ============================================================
# REGISTRATION
# ============================================================

def setup():
    from brain.agent import register_skill
    register_skill(PPTSkill())
